repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.10.1
    hooks:
    - id: check-autopkg-recipes
      args: [
          "--recipe-prefix=com.github.symmtree.",
          "--override-prefix=local.",
          "--",
      ]
    - id: forbid-autopkg-overrides
      exclude: ^RecipeOverrides/
    - id: forbid-autopkg-trust-info
      exclude: ^RecipeOverrides/
    - id: check-autopkg-recipe-list
  - repo: https://github.com/python/black
    rev: 21.11b1
    hooks:
      - id: black