Description: Signs a provided installer package using a signing certificate identifier.
Identifier: com.github.humanendpoint.sign.docker-buildx
ParentRecipe: com.github.humanendpoint.pkg.docker-buildx

Input:
  SIGNINGCERTIFICATE: 'Developer ID Installer: ()'

Process:
- Processor: com.github.rtrouton.SharedProcessors/PkgSigner
  Arguments:
    pkg_path: '%pkg_path%'
    signing_cert: '%SIGNINGCERTIFICATE%'
