Description: Downloads the latest version of Docker CLI.
Identifier: com.github.humanendpoint.download.docker-cli
MinimumVersion: '2.3'

Input:
  NAME: docker
  ARCH: aarch64

Process:
- Processor: URLTextSearcher
  Arguments:
    re_pattern: (\d+\.\d+\.\d+)
    result_output_var_name: version
    url: 'https://download.docker.com/mac/static/stable/%ARCH%'

- Processor: URLDownloaderPython
  Arguments:
    url: https://download.docker.com/mac/static/stable/%ARCH%/docker-%version%.tgz

- Processor: EndOfCheckPhase
