Description: Packages the latest version of docker-buildx.
Identifier: com.github.humanendpoint.pkg.docker-buildx
MinimumVersion: '2.3'
ParentRecipe: com.github.humanendpoint.download.docker-buildx

Input:
  NAME: docker-buildx

Process:
  - Processor: PkgRootCreator
    Arguments:
      pkgdirs:
        usr: '0755'
        usr/local: '0755'
        usr/local/bin: '0755'
      pkgroot: '%RECIPE_CACHE_DIR%/%NAME%'

  - Processor: FileFinder
    Arguments:
      pattern: '%RECIPE_CACHE_DIR%/downloads/buildx-v%version%.darwin-arm64'

  - Processor: Copier
    Arguments:
      source_path: '%found_filename%'
      destination_path: '%RECIPE_CACHE_DIR%/%NAME%/usr/local/bin/buildx-v%version%.darwin-arm64'

  - Processor: PkgCreator
    Arguments:
      pkg_request:
        pkgroot: '%RECIPE_CACHE_DIR%/%NAME%'
        chown:
        - group: staff
          path: usr
          user: root
        - group: staff
          path: usr/local
          user: root
        - group: staff
          path: usr/local/bin
          user: root
        id: com.docker.buildx
        version: '%version%'
        pkgname: 'docker-buildx-%version%'
        pkgtype: flat
        options: purge_ds_store
